### ISSUE TITLE
Test custom builds for socialhome

### ISSUE THREAD

**Issue by Zauberstuhl** [thefederationinfo/federation-tests#11]
related to #10 

@jaywink for that to work you have to;

* visit https://testsuite.the-federation.info/auth
* authorized the app with your github account (since socialhome is under your user-account you don't have to grant any extra permissons)
* add "socialhome" in the first field and "jaywink/socialhome" in the second field then hit enter

It should create a webhook and request permissions for updating commit statuses.
If you did all of that it *should* work :laughing:  (well we have to merge the PR first)

// edit; ok I had a stupid bug in my api calls but that is resolved with https://github.com/thefederationinfo/github-integration/commit/6e0618a812362738293c3417bd9cbac927b766f7 now also stranger will trigger the testsuite -> https://github.com/ganggo/federation/pull/17

**Comment by jaywink** [comment]
Done! Need to get a PR in now :)
