### ISSUE TITLE
Add socialhome image

### ISSUE THREAD

**Issue by Zauberstuhl** [thefederationinfo/federation-tests#4]
related to #3

**Comment by Zauberstuhl** [comment]
@jaywink by any chance.. do you already have a Dockerfile?

**Comment by jaywink** [comment]
@Zauberstuhl yes, or at least a kind of working dev env docker compose which has one dockerfile for django and one for the JS stuff. Personally I've not used it that much. I want to create a production image which will split all the services into separate containers. I guess for these tests something like the dev image would work better.

Check it out here, can we use it here? https://github.com/jaywink/socialhome/tree/master/docker/dev
